language: csharp
solution: sudokuSolver/sudokuSolver.sln
install:
  - nuget restore sudokuSolver/sudokuSolver.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release sudokuSolver/sudokuSolver.sln
  - mono testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe MyProject.Tests/bin/Release/MyProject.Tests.dll
