language: csharp
solution: sudokuSolver/sudokuSolver.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore sudokuSolver/sudokuSolver.sln
after_script:
  - nunit-console sudokuSolver/packages/NUnit.Console.3.7.0/NUnit.Console.3.7.0.nupkg
