language: csharp
script:
  - xbuild /p:Configuration=Debug sudokuSolver/sudokuSolver.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore sudokuSolver/sudokuSolver.sln
after_script:
  - nunit-console sudokuSolver/packages/NUnit.3.8.1/lib/net45/nunit.framework.dll
