language: csharp
solution: sudokuSolver/sudokuSolver.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore sudokuSolver/sudokuSolver.sln
after_script:
  - nunit-console CSC439-OS-Sudoku/sudokuSolver/sudokuSolver/bin/Debug/nunit.framework.dll
